// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Returns a hello world message",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "general"
                ],
                "summary": "Hello World",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the database and application",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/iss/crew": {
            "get": {
                "description": "Return current crew aboard the ISS",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Crew"
                ],
                "summary": "Get current ISS crew",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ISSCrewResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/iss/current": {
            "get": {
                "description": "Returns the current position of the International Space Station",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ISS"
                ],
                "summary": "Get Current ISS Position",
                "parameters": [
                    {
                        "enum": [
                            "kilometers",
                            "miles"
                        ],
                        "type": "string",
                        "default": "kilometers",
                        "description": "Units (kilometers or miles)",
                        "name": "units",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ISSPosition"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/iss/historical": {
            "post": {
                "description": "Returns the ISS position for a timestamp provided in request body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ISS"
                ],
                "summary": "Get Historical ISS Position (POST)",
                "parameters": [
                    {
                        "description": "Historical position request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.HistoricalRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ISSPosition"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/iss/historical/{timestamp}": {
            "get": {
                "description": "Returns the ISS position for a specific timestamp (within 4 hours back/forward)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ISS"
                ],
                "summary": "Get Historical ISS Position",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Unix timestamp",
                        "name": "timestamp",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "kilometers",
                            "miles"
                        ],
                        "type": "string",
                        "default": "kilometers",
                        "description": "Units (kilometers or miles)",
                        "name": "units",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ISSPosition"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/iss/range": {
            "get": {
                "description": "Returns all ISS positions within a specified time range",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ISS"
                ],
                "summary": "Get ISS Positions in Time Range",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Start timestamp (Unix)",
                        "name": "start_time",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "End timestamp (Unix)",
                        "name": "end_time",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "kilometers",
                            "miles"
                        ],
                        "type": "string",
                        "default": "kilometers",
                        "description": "Units (kilometers or miles)",
                        "name": "units",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ISSPosition"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/iss/status": {
            "get": {
                "description": "Returns statistics about ISS tracking data and system status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ISS"
                ],
                "summary": "Get ISS Tracking Status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Astronaut": {
            "type": "object",
            "properties": {
                "craft": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.AstronautWithPhoto": {
            "type": "object",
            "properties": {
                "imgUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.HistoricalRequest": {
            "type": "object",
            "required": [
                "timestamp"
            ],
            "properties": {
                "timestamp": {
                    "type": "integer"
                },
                "units": {
                    "type": "string"
                }
            }
        },
        "models.ISSCrewResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "people": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Astronaut"
                    }
                }
            }
        },
        "models.ISSCrewWithPhotosResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "people": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AstronautWithPhoto"
                    }
                }
            }
        },
        "models.ISSPosition": {
            "type": "object",
            "properties": {
                "altitude": {
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "daynum": {
                    "type": "number"
                },
                "footprint": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "name": {
                    "type": "string"
                },
                "solar_lat": {
                    "type": "number"
                },
                "solar_lon": {
                    "type": "number"
                },
                "timestamp": {
                    "type": "integer"
                },
                "units": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "velocity": {
                    "type": "number"
                },
                "visibility": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "ISS Model Backend API",
	Description:      "This is the ISS Model Backend API server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
