name: Deploy
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            
            cd /home/kni/iss-model-backend
            git stash
            git checkout main
            git pull
            
            # Use your existing make commands
            make docker-down
            make docker-run
            
            echo "$(date): ISS Model Backend deployed successfully" >> ../deploy-log.txt
            
            docker system prune -a -f
